### ISSUE TITLE
Resource and Deployment name inconsistent with Version Upgrade

### ISSUE THREAD

**Issue by iamTheL** [hyscale/hyscale#347]
Summary : 

After upgrading hyscale to the newest version, the naming convention for deployment, service, pods, etc changed from [namespace]-[service-name] to [service-name]. This leads to creating a new deployment, service, etc which is supposed to be the same as before.

**Comment by Nishanthnishu** [comment]
Hi Padmanabhan (@iamTheL)

Thanks for reporting the issue. The version 0.9.4.1 introduces breaking changes due to which you may end up creating new resources in K8s instead of updating existing resources.
 To resolve this issue, we have provided a migration script in release artifacts which migrates old resources to new resources preserving volumes intact.
